### PR TITLE
Am/ups test

### PR DESCRIPTION
**Pull request by aizadaM**
Please approve my PR for method upsPageOpenTest()

### CODE REVIEW

**Review by JuliaUbushieva — APPROVED** [review]

**Review by NYerlan — COMMENTED** [review]
I don't see any assertion in your test

**Comment by aizadaM** [comment]
@NYerlan I already deleted this branch on my local computer. So I created new PR with one assertion https://github.com/RedRoverSchool/JenkinsQA_07/pull/528

**Review by julijapakula — CHANGES_REQUESTED** [review]
No "test" prefix in the test name

**Comment by aizadaM** [comment]
@julijapakula Line 346 my code starts with @Test. Or am I misunderstanding something? Please let me know

**Comment by julijapakula** [comment]
> @julijapakula Line 346 my code starts with @test. Or am I misunderstanding something? Please let me know

**@Test** - this is annotation - shows testNG that this is a test
**public void upsPageOpenTest() { }** - name of the test. You have "Test" at the end of the name, but it should be in the begining - this was a reqest from Sergey. It`s been told do not approve commits in a wrong test name format.

**Comment by aizadaM** [comment]
@julijapakula Thank you! Completely missed it

**Pull request closed without merging**
