### PR TITLE
TC_09.001.02 | Manage Jenkins > Create User with valid data

### PR DESCRIPTION
**Pull request by MariannaLiss**
https://trello.com/c/Pe5znE9D/496-tc0900102-manage-jenkins-create-user-with-valid-data

### CODE REVIEW

**Comment by MalykhAV** [comment]
Please, write your TC.

**Comment by Yulia-Haia** [comment]
https://trello.com/c/E2OQGd0p/243-tc0000111-creating-new-item-creating-freestyle-project-with-empty-name 
Вот не лучший, но вариант карточки, с чего можно начать

**Review by Yulia-Haia — APPROVED** [review]

**Review by MalykhAV — CHANGES_REQUESTED** [review]
Check out a couple of Sergey's recent recordings in the review of tests.
We name commit by using TC, for e.g. TC_09.001.02 | Manage Jenkins > Add Test Create User with valid data. I'm not sure that this is a good practice to make xpathes to Const.

**Comment by MariannaLiss** [comment]
> Check out a couple of Sergey's recent recordings in the review of tests. We name commit by using TC, for e.g. TC_09.001.02 | Manage Jenkins > Add Test Create User with valid data. I'm not sure that this is a good practice to make xpathes to Const.

Я написала Вам в Slack

**Comment by MariannaLiss** [comment]
> Check out a couple of Sergey's recent recordings in the review of tests. We name commit by using TC, for e.g. TC_09.001.02 | Manage Jenkins > Add Test Create User with valid data. I'm not sure that this is a good practice to make xpathes to Const.

Снимите, пожалуйста, замечание. Мне не смерджить из-за него. Я учла на будущее информацию.

**Review by MalykhAV — APPROVED** [review]

**Pull request merged**
