### PR TITLE
RF_000.001 refactoring TC_04.001.02 > US_04.001

### PR DESCRIPTION
**Pull request by LenKopt**
https://trello.com/c/wAEFKBBw/123-rf000001-code-review-tc0400102-us04001

### CODE REVIEW

**Review by Sosnitsky-E — COMMENTED** [review]
Hello, it seems that for refactoring you need to create a new card and attach it to an existing test case

**Comment by LenKopt** [comment]
Thanks for your advice, I've already changed it

**Comment by LenKopt** [comment]
> Hello, it seems that for refactoring you need to create a new card and attach it to an existing test case

**Comment by LenKopt** [comment]
> > Hello, it seems that for refactoring you need to create a new card and attach it to an existing test case

Thanks for your advice, I've already changed it

**Comment by judmi** [comment]
Remove the commented code please. It's a bad practice to merge commented code into main.

**Comment by LenKopt** [comment]
> Remove the commented code please. It's a bad practice to merge commented code into main.

yes, in this case i can delete, but sometimes old code, may be, will necessary, if you are not sure in new code, I think this

**Review by RomanBurlaka78 — APPROVED** [review]

**Pull request merged**
