### PR TITLE
Tn/tc 00.001.16 | Create Freestyleproject

### PR DESCRIPTION
**Pull request by tnelyubova**
https://trello.com/c/zLBprqdt/401-tc0000116-creating-new-item-creating-freestyle-project

### CODE REVIEW

**Comment by EkaterinaSokolova-V** [comment]
It's better to do 2 PRs to separate 2 different tests.

**Comment by tnelyubova** [comment]
> It's better to do 2 PRs to separate 2 different tests.

Thanks for your comment, this is my first time, I didn't know. 
I don't understand how I can separete them now.. Could you approve it? 
In the future, I'll do a separate PR for each test!

**Comment by EkaterinaSokolova-V** [comment]
You can delete testCreateFreestyleProject() test from your code, then merge this PR and create new one with testCreateFreestyleProject().

**Comment by tnelyubova** [comment]
I deleted a superfluous test

**Comment by EkaterinaSokolova-V** [comment]
Please attach corresponding TC Trello card.

**Review by EkaterinaSokolova-V — APPROVED** [review]

**Comment by tnelyubova** [comment]
Done

**Review by nikabenz — APPROVED** [review]

**Pull request merged**
