### PR TITLE
RF_00.001.09. Delete a dublicate test. 

### PR DESCRIPTION
**Pull request by NadinLi**

### CODE REVIEW

**Review by judmi — COMMENTED** [review]
1. testCreate is not a very clear test name, better give a more clear one. So that one could understand what exactly is being tested without looking at its code.
2. PR name shall be the same as the TC's name
3. Link to the trello card?

**Comment by NadinLi** [comment]
Был конфликт с двумя одинаковыми именами. Удалила тест с таким же именем.

**Review by VictoriaLema — APPROVED** [review]

**Comment by NadinLi** [comment]
Delete a dublicate test.
https://trello.com/c/8r5LXNsc/330-rf0000109-creating-freestyle-project

**Comment by NadinLi** [comment]
[RF_00.001.09 | Delete a dublicate test.](https://trello.com/c/8r5LXNsc/330-rf0000109-delete-a-dublicate-test)

**Review by NataliiaBor1 — APPROVED** [review]

**Pull request closed without merging**
