### PR TITLE
TC_12.001.05 | Footer > Jenkins version > Viewing the Jenkins version

### PR DESCRIPTION
**Pull request by AnzhelikaLa**
https://trello.com/c/VwzZ3fZs/254-tc1200105-footer-jenkins-version-viewing-the-jenkins-version

### CODE REVIEW

**Comment by judmi** [comment]
In your TC card you have a click on the version but in this test you do not click anything. It's better to update either TC or the code so that they match

**Comment by Aki-Mira** [comment]
How can you verify that the Jenkins version is displayed in the lower right corner?

In your code you only verify number of version, you shoul change your TC or code

**Comment by AnzhelikaLa** [comment]
> In your TC card you have a click on the version but in this test you do not click anything. It's better to update either TC or the code so that they match

**Comment by AnzhelikaLa** [comment]
I corrected my TC. Thanks @Aki-Mira and @judmi for your advice

**Review by MarinaAvr — APPROVED** [review]

**Review by SafronovaOlga — APPROVED** [review]

**Pull request merged**
