### PR TITLE
TC_01.001.10 | 1. New test testEditProjectDescription was added. 2. R…

### PR DESCRIPTION
**Pull request by EvgenyJavaTest**
…efactoring: а test chain was created

Тесты взаимосвязаны. Для запуска теста testEditProjectDescription нужно запустить прогон всего класса FreestyleProject16Test. 

https://trello.com/c/rmS5mfNs/714-tc0100110-freestyle-project-edit-description

### CODE REVIEW

**Review by VictoriaLema — COMMENTED** [review]
Hi! Please, change the title of PR (it should be the same as Trello card title)

**Comment by EvgenyJavaTest** [comment]
> Hi! Please, change the title of PR (it should be the same as Trello card title)

The name of the pool request indicates the test case number "**TC_01.001.10**". Is there a rule that I need to completely copy the name of the test case? If so, I will ask you to share the source

**Comment by VictoriaLema** [comment]
> > Hi! Please, change the title of PR (it should be the same as Trello card title)
> 
> The name of the pool request indicates the test case number "**TC_01.001.10**". Is there a rule that I need to completely copy the name of the test case? If so, I will ask you to share the source



> > Hi! Please, change the title of PR (it should be the same as Trello card title)
> 
> The name of the pool request indicates the test case number "**TC_01.001.10**". Is there a rule that I need to completely copy the name of the test case? If so, I will ask you to share the source

I think it was lesson23 (10/24), second part.

**Comment by EvgenyJavaTest** [comment]
> I think it was lesson23 (10/24), second half.

The number of the test case must be written. The rest is optional. You can see in the screenshot

**Review by VictoriaLema — COMMENTED** [review]
There is a commit name on the screenshot. Task name is optional in commits. I meant PR title in my comment

**Review by VictoriaLema — COMMENTED** [review]
Also, as I remember, Sergey showed the process of working with Trello cards and Git hub twice in this lesson. The second time is the correct one.

**Comment by EvgenyJavaTest** [comment]
> There is a commit name on the screenshot. Task number is optional in commits indeed. I meant PR title in my comment

The name of the request pool is taken from the commit.




> Also, as I remember, Sergey showed the process of working with Trello cards and Git hub twice in this lesson. The second time is the correct one.

The screenshot I attached is just from the second example. Sergey explained at the lecture why it is important to indicate the number of the test case in the name of the pool request. The rest is optional.

**Review by SafronovaOlga — APPROVED** [review]

**Review by AliaksandrMakaranka — APPROVED** [review]

**Pull request merged**
