### PR TITLE
RF_06.003.05 | Organization folder > Rename Organization folder from drop down list

### PR DESCRIPTION
**Pull request by MartaShepel**
refactoring TC_06.003.05

### CODE REVIEW

**Review by VictoriaLema — COMMENTED** [review]
Hi! Please, attach the link to Trello card and change the name of PR (it should be the same as a Trello card name)

**Comment by MartaShepel** [comment]
https://trello.com/c/hy7FUUlm/771-rf0600305-item-sub-item-us-title

**Review by LiudmilaLobanova — APPROVED** [review]

**Review by VictoriaLema — COMMENTED** [review]
it is not your Trello card title

**Comment by MartaShepel** [comment]
https://trello.com/c/KKiK3X5n/596-tc0600305-organization-folder-rename-organization-folder-from-drop-down-list

**Review by VictoriaLema — COMMENTED** [review]
Your PR title should be 
RF_06.003.05 | Organization folder > Rename Organization folder from drop down list
(the same as Trello card title for this PR )

**Review by VictoriaLema — APPROVED** [review]

**Pull request merged**
