### PR TITLE
refactoringPOM

### PR DESCRIPTION
**Pull request by maksin82**
https://trello.com/c/yieKWSIV
https://trello.com/c/kdBZCkRh
https://trello.com/c/b6C7ypTe
https://trello.com/c/2SlzsHLU

### CODE REVIEW

**Comment by maksin82** [comment]
[RF_05.002.03 | Multibranch pipeline > Rename Multibranch pipeline > Verify that the Multibranch pipeline could be renamed through the sidebar](https://trello.com/c/2SlzsHLU/1021-rf0500203-multibranch-pipeline-rename-multibranch-pipeline-verify-that-the-multibranch-pipeline-could-be-renamed-through-the-sid)

**Comment by maksin82** [comment]
[RF_05.002.06 | Multibranch pipeline > Rename Multibranch pipeline](https://trello.com/c/b6C7ypTe/1023-rf0500206-multibranch-pipeline-rename-multibranch-pipeline)

**Comment by maksin82** [comment]
[RF_05.002.04 | Multibranch pipeline > Rename Multibranch pipeline](https://trello.com/c/kdBZCkRh/1024-rf0500204-multibranch-pipeline-rename-multibranch-pipeline)

**Comment by maksin82** [comment]
[RF_05.002.05 | Multibranch pipeline > Rename Multibranch pipeline](https://trello.com/c/yieKWSIV/1022-rf0500205-multibranch-pipeline-rename-multibranch-pipeline)

**Review by NataliiaBor1 — APPROVED** [review]

**Review by biletskaanastasiiia — APPROVED** [review]

**Pull request merged**
